version: "3.8"

services:
  mysql: # docker-compose run mysql bash
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - .docker/mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 3304:3306
  php: # docker-compose run php bash
    build: './.docker/php'
    ports:
      - "8888:80"
    tty: true
    environment:
      PHP_IDE_CONFIG: "serverName=Laravel-Learning Docker"
    volumes:
      - ./:/var/www/html/
      - ./.docker/php/logs/:/var/log/apache2/
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  composer: # docker-compose run composer bash
    build: './.docker/composer'
    tty: true
    command: [ "composer", "update" ]
    volumes:
      - ./:/app/
      - ./.docker/composer/tmp/:/tmp/
    depends_on:
      - php